[build]
  functions = "netlify-functions"
  publish = "server"

[dev]
  functions = "netlify-functions"

  exports.handler = async function(event, context) {
  return {
    statusCode: 200,
    body: JSON.stringify({ message: "Hello from Netlify Functions!" })
  };
};

